// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddDepositData, AddDepositErrors, AddDepositResponses, AddGoalData, AddGoalErrors, AddGoalResponses, CountGoalData, CountGoalErrors, CountGoalResponses, DeleteDepositData, DeleteDepositErrors, DeleteDepositResponses, DeleteGoalData, DeleteGoalErrors, DeleteGoalResponses, FetchDepositsData, FetchDepositsErrors, FetchDepositsResponses, FetchGoalsData, FetchGoalsErrors, FetchGoalsResponses, GetDepositData, GetDepositErrors, GetDepositResponses, GetGoalData, GetGoalErrors, GetGoalResponses, ReadRootGetData, ReadRootGetResponses, TotalDepositData, TotalDepositErrors, TotalDepositResponses, UpdateGoalData, UpdateGoalErrors, UpdateGoalResponses, UpsertBulkGoalData, UpsertBulkGoalErrors, UpsertBulkGoalResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>): RequestResult<ReadRootGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Count Goal
 */
export const countGoal = <ThrowOnError extends boolean = false>(options?: Options<CountGoalData, ThrowOnError>): RequestResult<CountGoalResponses, CountGoalErrors, ThrowOnError> => (options?.client ?? client).get<CountGoalResponses, CountGoalErrors, ThrowOnError>({ url: '/goals/count', ...options });

/**
 * Delete
 */
export const deleteGoal = <ThrowOnError extends boolean = false>(options: Options<DeleteGoalData, ThrowOnError>): RequestResult<DeleteGoalResponses, DeleteGoalErrors, ThrowOnError> => (options.client ?? client).delete<DeleteGoalResponses, DeleteGoalErrors, ThrowOnError>({ url: '/goals/{id}', ...options });

/**
 * Get Goal
 */
export const getGoal = <ThrowOnError extends boolean = false>(options: Options<GetGoalData, ThrowOnError>): RequestResult<GetGoalResponses, GetGoalErrors, ThrowOnError> => (options.client ?? client).get<GetGoalResponses, GetGoalErrors, ThrowOnError>({ url: '/goals/{id}', ...options });

/**
 * Update
 */
export const updateGoal = <ThrowOnError extends boolean = false>(options: Options<UpdateGoalData, ThrowOnError>): RequestResult<UpdateGoalResponses, UpdateGoalErrors, ThrowOnError> => (options.client ?? client).put<UpdateGoalResponses, UpdateGoalErrors, ThrowOnError>({
    url: '/goals/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List
 */
export const fetchGoals = <ThrowOnError extends boolean = false>(options?: Options<FetchGoalsData, ThrowOnError>): RequestResult<FetchGoalsResponses, FetchGoalsErrors, ThrowOnError> => (options?.client ?? client).get<FetchGoalsResponses, FetchGoalsErrors, ThrowOnError>({ url: '/goals', ...options });

/**
 * Add
 */
export const addGoal = <ThrowOnError extends boolean = false>(options: Options<AddGoalData, ThrowOnError>): RequestResult<AddGoalResponses, AddGoalErrors, ThrowOnError> => (options.client ?? client).post<AddGoalResponses, AddGoalErrors, ThrowOnError>({
    url: '/goals',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Bulk Upsert
 */
export const upsertBulkGoal = <ThrowOnError extends boolean = false>(options: Options<UpsertBulkGoalData, ThrowOnError>): RequestResult<UpsertBulkGoalResponses, UpsertBulkGoalErrors, ThrowOnError> => (options.client ?? client).post<UpsertBulkGoalResponses, UpsertBulkGoalErrors, ThrowOnError>({
    url: '/goals/bulk',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteDeposit = <ThrowOnError extends boolean = false>(options: Options<DeleteDepositData, ThrowOnError>): RequestResult<DeleteDepositResponses, DeleteDepositErrors, ThrowOnError> => (options.client ?? client).delete<DeleteDepositResponses, DeleteDepositErrors, ThrowOnError>({ url: '/deposit/{id}', ...options });

/**
 * Get
 */
export const getDeposit = <ThrowOnError extends boolean = false>(options: Options<GetDepositData, ThrowOnError>): RequestResult<GetDepositResponses, GetDepositErrors, ThrowOnError> => (options.client ?? client).get<GetDepositResponses, GetDepositErrors, ThrowOnError>({ url: '/deposit/{id}', ...options });

/**
 * Add
 */
export const addDeposit = <ThrowOnError extends boolean = false>(options: Options<AddDepositData, ThrowOnError>): RequestResult<AddDepositResponses, AddDepositErrors, ThrowOnError> => (options.client ?? client).post<AddDepositResponses, AddDepositErrors, ThrowOnError>({
    url: '/deposit/add',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List
 */
export const fetchDeposits = <ThrowOnError extends boolean = false>(options?: Options<FetchDepositsData, ThrowOnError>): RequestResult<FetchDepositsResponses, FetchDepositsErrors, ThrowOnError> => (options?.client ?? client).get<FetchDepositsResponses, FetchDepositsErrors, ThrowOnError>({ url: '/deposit', ...options });

/**
 * Total
 */
export const totalDeposit = <ThrowOnError extends boolean = false>(options: Options<TotalDepositData, ThrowOnError>): RequestResult<TotalDepositResponses, TotalDepositErrors, ThrowOnError> => (options.client ?? client).post<TotalDepositResponses, TotalDepositErrors, ThrowOnError>({
    url: '/deposit/total',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
