// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * DepositCreateSchema
 */
export type DepositCreateSchema = {
    /**
     * Amount
     */
    amount: number;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Goal Id
     */
    goal_id: number;
};

/**
 * DepositPaginationSchema
 */
export type DepositPaginationSchema = {
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Page
     */
    page: number;
    /**
     * Data
     */
    data?: Array<DepositSchema>;
    /**
     * Sum
     */
    sum?: number;
};

/**
 * DepositSchema
 */
export type DepositSchema = {
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Id
     */
    id: number;
    /**
     * Amount
     */
    amount: number;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Goal Id
     */
    goal_id: number;
};

/**
 * GoalCreateSchema
 */
export type GoalCreateSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Target
     */
    target: number;
    /**
     * Active
     */
    active: boolean;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * GoalPaginationSchema
 */
export type GoalPaginationSchema = {
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Page
     */
    page: number;
    /**
     * Data
     */
    data: Array<GoalSchema>;
};

/**
 * GoalSchema
 */
export type GoalSchema = {
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Target
     */
    target: number;
    /**
     * Active
     */
    active: boolean;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CountGoalsCountGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Active
         */
        active?: boolean;
    };
    url: '/goals/count';
};

export type CountGoalsCountGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CountGoalsCountGetError = CountGoalsCountGetErrors[keyof CountGoalsCountGetErrors];

export type CountGoalsCountGetResponses = {
    /**
     * Response Count Goals Count Get
     *
     * Successful Response
     */
    200: number;
};

export type CountGoalsCountGetResponse = CountGoalsCountGetResponses[keyof CountGoalsCountGetResponses];

export type DeleteGoalsIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/goals/{id}';
};

export type DeleteGoalsIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGoalsIdDeleteError = DeleteGoalsIdDeleteErrors[keyof DeleteGoalsIdDeleteErrors];

export type DeleteGoalsIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGoalsIdDeleteResponse = DeleteGoalsIdDeleteResponses[keyof DeleteGoalsIdDeleteResponses];

export type GetGoalsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/goals/{id}';
};

export type GetGoalsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGoalsIdGetError = GetGoalsIdGetErrors[keyof GetGoalsIdGetErrors];

export type GetGoalsIdGetResponses = {
    /**
     * Successful Response
     */
    200: GoalSchema;
};

export type GetGoalsIdGetResponse = GetGoalsIdGetResponses[keyof GetGoalsIdGetResponses];

export type ListGoalsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/goals';
};

export type ListGoalsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGoalsGetError = ListGoalsGetErrors[keyof ListGoalsGetErrors];

export type ListGoalsGetResponses = {
    /**
     * Successful Response
     */
    200: GoalPaginationSchema;
};

export type ListGoalsGetResponse = ListGoalsGetResponses[keyof ListGoalsGetResponses];

export type UpsertGoalsPostData = {
    body: GoalCreateSchema;
    path?: never;
    query?: never;
    url: '/goals';
};

export type UpsertGoalsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertGoalsPostError = UpsertGoalsPostErrors[keyof UpsertGoalsPostErrors];

export type UpsertGoalsPostResponses = {
    /**
     * Successful Response
     */
    201: GoalSchema;
};

export type UpsertGoalsPostResponse = UpsertGoalsPostResponses[keyof UpsertGoalsPostResponses];

export type DeleteDepositIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/deposit/{id}';
};

export type DeleteDepositIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDepositIdDeleteError = DeleteDepositIdDeleteErrors[keyof DeleteDepositIdDeleteErrors];

export type DeleteDepositIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDepositIdDeleteResponse = DeleteDepositIdDeleteResponses[keyof DeleteDepositIdDeleteResponses];

export type GetDepositIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/deposit/{id}';
};

export type GetDepositIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDepositIdGetError = GetDepositIdGetErrors[keyof GetDepositIdGetErrors];

export type GetDepositIdGetResponses = {
    /**
     * Successful Response
     */
    200: DepositSchema;
};

export type GetDepositIdGetResponse = GetDepositIdGetResponses[keyof GetDepositIdGetResponses];

export type AddDepositAddPostData = {
    body: DepositCreateSchema;
    path?: never;
    query?: never;
    url: '/deposit/add';
};

export type AddDepositAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddDepositAddPostError = AddDepositAddPostErrors[keyof AddDepositAddPostErrors];

export type AddDepositAddPostResponses = {
    /**
     * Successful Response
     */
    200: DepositSchema;
};

export type AddDepositAddPostResponse = AddDepositAddPostResponses[keyof AddDepositAddPostResponses];

export type ListDepositPostData = {
    /**
     * Id
     */
    body?: Array<number>;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Deposit Date
         */
        deposit_date?: string | null;
    };
    url: '/deposit';
};

export type ListDepositPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDepositPostError = ListDepositPostErrors[keyof ListDepositPostErrors];

export type ListDepositPostResponses = {
    /**
     * Successful Response
     */
    200: DepositPaginationSchema;
};

export type ListDepositPostResponse = ListDepositPostResponses[keyof ListDepositPostResponses];

export type TotalDepositTotalPostData = {
    /**
     * Goals
     */
    body: Array<number>;
    path?: never;
    query?: never;
    url: '/deposit/total';
};

export type TotalDepositTotalPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TotalDepositTotalPostError = TotalDepositTotalPostErrors[keyof TotalDepositTotalPostErrors];

export type TotalDepositTotalPostResponses = {
    /**
     * Response Total Deposit Total Post
     *
     * Successful Response
     */
    200: number;
};

export type TotalDepositTotalPostResponse = TotalDepositTotalPostResponses[keyof TotalDepositTotalPostResponses];
