// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * GoalCreateSchema
 */
export type GoalCreateSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Target
     */
    target: number;
    /**
     * Deadline
     */
    deadline: string;
};

/**
 * GoalPaginationSchema
 */
export type GoalPaginationSchema = {
    /**
     * Total
     */
    total: number;
    /**
     * Data
     */
    data: Array<GoalSchema>;
};

/**
 * GoalSchema
 */
export type GoalSchema = {
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Target
     */
    target: number;
    /**
     * Active
     */
    active: boolean;
    /**
     * Deadline
     */
    deadline: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListGoalsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/goals/';
};

export type ListGoalsGetResponses = {
    /**
     * Successful Response
     */
    200: GoalPaginationSchema;
};

export type ListGoalsGetResponse = ListGoalsGetResponses[keyof ListGoalsGetResponses];

export type CreateGoalsPostData = {
    body: GoalCreateSchema;
    path?: never;
    query?: never;
    url: '/goals/';
};

export type CreateGoalsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGoalsPostError = CreateGoalsPostErrors[keyof CreateGoalsPostErrors];

export type CreateGoalsPostResponses = {
    /**
     * Successful Response
     */
    201: GoalSchema;
};

export type CreateGoalsPostResponse = CreateGoalsPostResponses[keyof CreateGoalsPostResponses];

export type DeleteGoalsIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/goals/{id}';
};

export type DeleteGoalsIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGoalsIdDeleteError = DeleteGoalsIdDeleteErrors[keyof DeleteGoalsIdDeleteErrors];

export type DeleteGoalsIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGoalsIdDeleteResponse = DeleteGoalsIdDeleteResponses[keyof DeleteGoalsIdDeleteResponses];
