// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * DepositCreateSchema
 */
export type DepositCreateSchema = {
    /**
     * Amount
     */
    amount: number;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Goal Id
     */
    goal_id: string;
};

/**
 * DepositPaginationSchema
 */
export type DepositPaginationSchema = {
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Page
     */
    page: number;
    /**
     * Data
     */
    data?: Array<DepositSchema>;
    /**
     * Sum
     */
    sum?: number;
};

/**
 * DepositSchema
 */
export type DepositSchema = {
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Id
     */
    id: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Goal Id
     */
    goal_id: string;
};

/**
 * GoalCreateSchema
 */
export type GoalCreateSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Target
     */
    target: number;
    /**
     * Active
     */
    active?: boolean;
    /**
     * Completed
     */
    completed?: boolean;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * GoalPaginationSchema
 */
export type GoalPaginationSchema = {
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Page
     */
    page: number;
    /**
     * Data
     */
    data: Array<GoalSchema>;
};

/**
 * GoalSchema
 */
export type GoalSchema = {
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Target
     */
    target: number;
    /**
     * Active
     */
    active: boolean;
    /**
     * Completed
     */
    completed: boolean;
    /**
     * Amount
     */
    amount: number;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * GoalUpdateSchema
 */
export type GoalUpdateSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Target
     */
    target: number;
    /**
     * Active
     */
    active?: boolean;
    /**
     * Completed
     */
    completed?: boolean;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CountGoalData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Active
         */
        active?: boolean | null;
        /**
         * Completed
         */
        completed?: boolean | null;
    };
    url: '/goals/count';
};

export type CountGoalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CountGoalError = CountGoalErrors[keyof CountGoalErrors];

export type CountGoalResponses = {
    /**
     * Response Countgoal
     *
     * Successful Response
     */
    200: number;
};

export type CountGoalResponse = CountGoalResponses[keyof CountGoalResponses];

export type DeleteGoalData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/goals/{id}';
};

export type DeleteGoalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGoalError = DeleteGoalErrors[keyof DeleteGoalErrors];

export type DeleteGoalResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGoalResponse = DeleteGoalResponses[keyof DeleteGoalResponses];

export type GetGoalData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/goals/{id}';
};

export type GetGoalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGoalError = GetGoalErrors[keyof GetGoalErrors];

export type GetGoalResponses = {
    /**
     * Successful Response
     */
    200: GoalSchema;
};

export type GetGoalResponse = GetGoalResponses[keyof GetGoalResponses];

export type UpdateGoalData = {
    body: GoalUpdateSchema;
    path?: never;
    query?: never;
    url: '/goals/{id}';
};

export type UpdateGoalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGoalError = UpdateGoalErrors[keyof UpdateGoalErrors];

export type UpdateGoalResponses = {
    /**
     * Successful Response
     */
    201: GoalSchema;
};

export type UpdateGoalResponse = UpdateGoalResponses[keyof UpdateGoalResponses];

export type FetchGoalsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/goals';
};

export type FetchGoalsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FetchGoalsError = FetchGoalsErrors[keyof FetchGoalsErrors];

export type FetchGoalsResponses = {
    /**
     * Successful Response
     */
    200: GoalPaginationSchema;
};

export type FetchGoalsResponse = FetchGoalsResponses[keyof FetchGoalsResponses];

export type AddGoalData = {
    body: GoalCreateSchema;
    path?: never;
    query?: never;
    url: '/goals';
};

export type AddGoalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddGoalError = AddGoalErrors[keyof AddGoalErrors];

export type AddGoalResponses = {
    /**
     * Successful Response
     */
    201: GoalSchema;
};

export type AddGoalResponse = AddGoalResponses[keyof AddGoalResponses];

export type DeleteDepositData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/deposit/{id}';
};

export type DeleteDepositErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDepositError = DeleteDepositErrors[keyof DeleteDepositErrors];

export type DeleteDepositResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDepositResponse = DeleteDepositResponses[keyof DeleteDepositResponses];

export type GetDepositData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/deposit/{id}';
};

export type GetDepositErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDepositError = GetDepositErrors[keyof GetDepositErrors];

export type GetDepositResponses = {
    /**
     * Successful Response
     */
    200: DepositSchema;
};

export type GetDepositResponse = GetDepositResponses[keyof GetDepositResponses];

export type AddDepositData = {
    body: DepositCreateSchema;
    path?: never;
    query?: never;
    url: '/deposit/add';
};

export type AddDepositErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddDepositError = AddDepositErrors[keyof AddDepositErrors];

export type AddDepositResponses = {
    /**
     * Successful Response
     */
    200: DepositSchema;
};

export type AddDepositResponse = AddDepositResponses[keyof AddDepositResponses];

export type FetchDepositsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Goal Id
         */
        goal_id?: Array<string>;
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Deposit Date
         */
        deposit_date?: string | null;
    };
    url: '/deposit';
};

export type FetchDepositsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FetchDepositsError = FetchDepositsErrors[keyof FetchDepositsErrors];

export type FetchDepositsResponses = {
    /**
     * Successful Response
     */
    200: DepositPaginationSchema;
};

export type FetchDepositsResponse = FetchDepositsResponses[keyof FetchDepositsResponses];

export type TotalDepositData = {
    /**
     * Goals
     */
    body: Array<number>;
    path?: never;
    query?: never;
    url: '/deposit/total';
};

export type TotalDepositErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TotalDepositError = TotalDepositErrors[keyof TotalDepositErrors];

export type TotalDepositResponses = {
    /**
     * Response Totaldeposit
     *
     * Successful Response
     */
    200: number;
};

export type TotalDepositResponse = TotalDepositResponses[keyof TotalDepositResponses];
