// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addDeposit, countGoal, deleteDeposit, deleteGoal, fetchDeposits, fetchGoals, getDeposit, getGoal, type Options, readRootGet, totalDeposit, upsertGoal } from '../sdk.gen';
import type { AddDepositData, AddDepositError, AddDepositResponse, CountGoalData, CountGoalError, CountGoalResponse, DeleteDepositData, DeleteDepositError, DeleteDepositResponse, DeleteGoalData, DeleteGoalError, DeleteGoalResponse, FetchDepositsData, FetchDepositsError, FetchDepositsResponse, FetchGoalsData, FetchGoalsError, FetchGoalsResponse, GetDepositData, GetDepositError, GetDepositResponse, GetGoalData, GetGoalError, GetGoalResponse, ReadRootGetData, TotalDepositData, TotalDepositError, TotalDepositResponse, UpsertGoalData, UpsertGoalError, UpsertGoalResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const readRootGetQueryKey = (options?: Options<ReadRootGetData>) => createQueryKey('readRootGet', options);

/**
 * Read Root
 */
export const readRootGetOptions = (options?: Options<ReadRootGetData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof readRootGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRootGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRootGetQueryKey(options)
});

export const countGoalQueryKey = (options?: Options<CountGoalData>) => createQueryKey('countGoal', options);

/**
 * Count
 */
export const countGoalOptions = (options?: Options<CountGoalData>) => queryOptions<CountGoalResponse, CountGoalError, CountGoalResponse, ReturnType<typeof countGoalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await countGoal({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: countGoalQueryKey(options)
});

export type MutationKey<TOptions extends Partial<Options>> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        tags?: ReadonlyArray<string>;
    }
];

const createMutationKey = <TOptions extends Partial<Options>>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    MutationKey<TOptions>[0]
] => {
    const params: MutationKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl };
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const deleteGoalMutationKey = (options?: Partial<Options<DeleteGoalData>>) => createMutationKey('deleteGoal', options);

/**
 * Delete
 */
export const deleteGoalMutation = (options?: Partial<Options<DeleteGoalData>>): UseMutationOptions<DeleteGoalResponse, DeleteGoalError, Options<DeleteGoalData>> => {
    const mutationOptions: UseMutationOptions<DeleteGoalResponse, DeleteGoalError, Options<DeleteGoalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteGoal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: deleteGoalMutationKey(options)
    };
    return mutationOptions;
};

export const getGoalQueryKey = (options: Options<GetGoalData>) => createQueryKey('getGoal', options);

/**
 * Get
 */
export const getGoalOptions = (options: Options<GetGoalData>) => queryOptions<GetGoalResponse, GetGoalError, GetGoalResponse, ReturnType<typeof getGoalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGoal({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGoalQueryKey(options)
});

export const fetchGoalsQueryKey = (options?: Options<FetchGoalsData>) => createQueryKey('fetchGoals', options);

/**
 * List
 */
export const fetchGoalsOptions = (options?: Options<FetchGoalsData>) => queryOptions<FetchGoalsResponse, FetchGoalsError, FetchGoalsResponse, ReturnType<typeof fetchGoalsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await fetchGoals({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: fetchGoalsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const fetchGoalsInfiniteQueryKey = (options?: Options<FetchGoalsData>): QueryKey<Options<FetchGoalsData>> => createQueryKey('fetchGoals', options, true);

/**
 * List
 */
export const fetchGoalsInfiniteOptions = (options?: Options<FetchGoalsData>) => {
    const opts = infiniteQueryOptions<FetchGoalsResponse, FetchGoalsError, InfiniteData<FetchGoalsResponse>, QueryKey<Options<FetchGoalsData>>, number | Pick<QueryKey<Options<FetchGoalsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<FetchGoalsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await fetchGoals({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: fetchGoalsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const upsertGoalMutationKey = (options?: Partial<Options<UpsertGoalData>>) => createMutationKey('upsertGoal', options);

/**
 * Upsert
 */
export const upsertGoalMutation = (options?: Partial<Options<UpsertGoalData>>): UseMutationOptions<UpsertGoalResponse, UpsertGoalError, Options<UpsertGoalData>> => {
    const mutationOptions: UseMutationOptions<UpsertGoalResponse, UpsertGoalError, Options<UpsertGoalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await upsertGoal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: upsertGoalMutationKey(options)
    };
    return mutationOptions;
};

export const deleteDepositMutationKey = (options?: Partial<Options<DeleteDepositData>>) => createMutationKey('deleteDeposit', options);

/**
 * Delete
 */
export const deleteDepositMutation = (options?: Partial<Options<DeleteDepositData>>): UseMutationOptions<DeleteDepositResponse, DeleteDepositError, Options<DeleteDepositData>> => {
    const mutationOptions: UseMutationOptions<DeleteDepositResponse, DeleteDepositError, Options<DeleteDepositData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteDeposit({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: deleteDepositMutationKey(options)
    };
    return mutationOptions;
};

export const getDepositQueryKey = (options: Options<GetDepositData>) => createQueryKey('getDeposit', options);

/**
 * Get
 */
export const getDepositOptions = (options: Options<GetDepositData>) => queryOptions<GetDepositResponse, GetDepositError, GetDepositResponse, ReturnType<typeof getDepositQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDeposit({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDepositQueryKey(options)
});

export const addDepositMutationKey = (options?: Partial<Options<AddDepositData>>) => createMutationKey('addDeposit', options);

/**
 * Add
 */
export const addDepositMutation = (options?: Partial<Options<AddDepositData>>): UseMutationOptions<AddDepositResponse, AddDepositError, Options<AddDepositData>> => {
    const mutationOptions: UseMutationOptions<AddDepositResponse, AddDepositError, Options<AddDepositData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addDeposit({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: addDepositMutationKey(options)
    };
    return mutationOptions;
};

export const fetchDepositsQueryKey = (options?: Options<FetchDepositsData>) => createQueryKey('fetchDeposits', options);

/**
 * List
 */
export const fetchDepositsOptions = (options?: Options<FetchDepositsData>) => queryOptions<FetchDepositsResponse, FetchDepositsError, FetchDepositsResponse, ReturnType<typeof fetchDepositsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await fetchDeposits({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: fetchDepositsQueryKey(options)
});

export const fetchDepositsInfiniteQueryKey = (options?: Options<FetchDepositsData>): QueryKey<Options<FetchDepositsData>> => createQueryKey('fetchDeposits', options, true);

/**
 * List
 */
export const fetchDepositsInfiniteOptions = (options?: Options<FetchDepositsData>) => {
    const opts = infiniteQueryOptions<FetchDepositsResponse, FetchDepositsError, InfiniteData<FetchDepositsResponse>, QueryKey<Options<FetchDepositsData>>, number | Pick<QueryKey<Options<FetchDepositsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<FetchDepositsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await fetchDeposits({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: fetchDepositsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const totalDepositMutationKey = (options?: Partial<Options<TotalDepositData>>) => createMutationKey('totalDeposit', options);

/**
 * Total
 */
export const totalDepositMutation = (options?: Partial<Options<TotalDepositData>>): UseMutationOptions<TotalDepositResponse, TotalDepositError, Options<TotalDepositData>> => {
    const mutationOptions: UseMutationOptions<TotalDepositResponse, TotalDepositError, Options<TotalDepositData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await totalDeposit({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: totalDepositMutationKey(options)
    };
    return mutationOptions;
};
