// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addDepositAddPost, countGoal, deleteDepositIdDelete, deleteGoal, fetchGoals, getDepositIdGet, getGoal, listDepositGet, type Options, readRootGet, totalDepositTotalPost, upsertGoal } from '../sdk.gen';
import type { AddDepositAddPostData, AddDepositAddPostError, AddDepositAddPostResponse, CountGoalData, CountGoalError, CountGoalResponse, DeleteDepositIdDeleteData, DeleteDepositIdDeleteError, DeleteDepositIdDeleteResponse, DeleteGoalData, DeleteGoalError, DeleteGoalResponse, FetchGoalsData, FetchGoalsError, FetchGoalsResponse, GetDepositIdGetData, GetDepositIdGetError, GetDepositIdGetResponse, GetGoalData, GetGoalError, GetGoalResponse, ListDepositGetData, ListDepositGetError, ListDepositGetResponse, ReadRootGetData, TotalDepositTotalPostData, TotalDepositTotalPostError, TotalDepositTotalPostResponse, UpsertGoalData, UpsertGoalError, UpsertGoalResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const readRootGetQueryKey = (options?: Options<ReadRootGetData>) => createQueryKey('readRootGet', options);

/**
 * Read Root
 */
export const readRootGetOptions = (options?: Options<ReadRootGetData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof readRootGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRootGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRootGetQueryKey(options)
});

export const countGoalQueryKey = (options?: Options<CountGoalData>) => createQueryKey('countGoal', options);

/**
 * Count
 */
export const countGoalOptions = (options?: Options<CountGoalData>) => queryOptions<CountGoalResponse, CountGoalError, CountGoalResponse, ReturnType<typeof countGoalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await countGoal({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: countGoalQueryKey(options)
});

export type MutationKey<TOptions extends Partial<Options>> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        tags?: ReadonlyArray<string>;
    }
];

const createMutationKey = <TOptions extends Partial<Options>>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    MutationKey<TOptions>[0]
] => {
    const params: MutationKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl };
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const deleteGoalMutationKey = (options?: Partial<Options<DeleteGoalData>>) => createMutationKey('deleteGoal', options);

/**
 * Delete
 */
export const deleteGoalMutation = (options?: Partial<Options<DeleteGoalData>>): UseMutationOptions<DeleteGoalResponse, DeleteGoalError, Options<DeleteGoalData>> => {
    const mutationOptions: UseMutationOptions<DeleteGoalResponse, DeleteGoalError, Options<DeleteGoalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteGoal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: deleteGoalMutationKey(options)
    };
    return mutationOptions;
};

export const getGoalQueryKey = (options: Options<GetGoalData>) => createQueryKey('getGoal', options);

/**
 * Get
 */
export const getGoalOptions = (options: Options<GetGoalData>) => queryOptions<GetGoalResponse, GetGoalError, GetGoalResponse, ReturnType<typeof getGoalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGoal({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGoalQueryKey(options)
});

export const fetchGoalsQueryKey = (options?: Options<FetchGoalsData>) => createQueryKey('fetchGoals', options);

/**
 * List
 */
export const fetchGoalsOptions = (options?: Options<FetchGoalsData>) => queryOptions<FetchGoalsResponse, FetchGoalsError, FetchGoalsResponse, ReturnType<typeof fetchGoalsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await fetchGoals({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: fetchGoalsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const fetchGoalsInfiniteQueryKey = (options?: Options<FetchGoalsData>): QueryKey<Options<FetchGoalsData>> => createQueryKey('fetchGoals', options, true);

/**
 * List
 */
export const fetchGoalsInfiniteOptions = (options?: Options<FetchGoalsData>) => {
    const opts = infiniteQueryOptions<FetchGoalsResponse, FetchGoalsError, InfiniteData<FetchGoalsResponse>, QueryKey<Options<FetchGoalsData>>, number | Pick<QueryKey<Options<FetchGoalsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<FetchGoalsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await fetchGoals({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: fetchGoalsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const upsertGoalMutationKey = (options?: Partial<Options<UpsertGoalData>>) => createMutationKey('upsertGoal', options);

/**
 * Upsert
 */
export const upsertGoalMutation = (options?: Partial<Options<UpsertGoalData>>): UseMutationOptions<UpsertGoalResponse, UpsertGoalError, Options<UpsertGoalData>> => {
    const mutationOptions: UseMutationOptions<UpsertGoalResponse, UpsertGoalError, Options<UpsertGoalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await upsertGoal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: upsertGoalMutationKey(options)
    };
    return mutationOptions;
};

export const deleteDepositIdDeleteMutationKey = (options?: Partial<Options<DeleteDepositIdDeleteData>>) => createMutationKey('deleteDepositIdDelete', options);

/**
 * Delete
 */
export const deleteDepositIdDeleteMutation = (options?: Partial<Options<DeleteDepositIdDeleteData>>): UseMutationOptions<DeleteDepositIdDeleteResponse, DeleteDepositIdDeleteError, Options<DeleteDepositIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteDepositIdDeleteResponse, DeleteDepositIdDeleteError, Options<DeleteDepositIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteDepositIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: deleteDepositIdDeleteMutationKey(options)
    };
    return mutationOptions;
};

export const getDepositIdGetQueryKey = (options: Options<GetDepositIdGetData>) => createQueryKey('getDepositIdGet', options);

/**
 * Get
 */
export const getDepositIdGetOptions = (options: Options<GetDepositIdGetData>) => queryOptions<GetDepositIdGetResponse, GetDepositIdGetError, GetDepositIdGetResponse, ReturnType<typeof getDepositIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDepositIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDepositIdGetQueryKey(options)
});

export const addDepositAddPostMutationKey = (options?: Partial<Options<AddDepositAddPostData>>) => createMutationKey('addDepositAddPost', options);

/**
 * Add
 */
export const addDepositAddPostMutation = (options?: Partial<Options<AddDepositAddPostData>>): UseMutationOptions<AddDepositAddPostResponse, AddDepositAddPostError, Options<AddDepositAddPostData>> => {
    const mutationOptions: UseMutationOptions<AddDepositAddPostResponse, AddDepositAddPostError, Options<AddDepositAddPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addDepositAddPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: addDepositAddPostMutationKey(options)
    };
    return mutationOptions;
};

export const listDepositGetQueryKey = (options?: Options<ListDepositGetData>) => createQueryKey('listDepositGet', options);

/**
 * List
 */
export const listDepositGetOptions = (options?: Options<ListDepositGetData>) => queryOptions<ListDepositGetResponse, ListDepositGetError, ListDepositGetResponse, ReturnType<typeof listDepositGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listDepositGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listDepositGetQueryKey(options)
});

export const listDepositGetInfiniteQueryKey = (options?: Options<ListDepositGetData>): QueryKey<Options<ListDepositGetData>> => createQueryKey('listDepositGet', options, true);

/**
 * List
 */
export const listDepositGetInfiniteOptions = (options?: Options<ListDepositGetData>) => {
    const opts = infiniteQueryOptions<ListDepositGetResponse, ListDepositGetError, InfiniteData<ListDepositGetResponse>, QueryKey<Options<ListDepositGetData>>, number | Pick<QueryKey<Options<ListDepositGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListDepositGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listDepositGet({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listDepositGetInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const totalDepositTotalPostMutationKey = (options?: Partial<Options<TotalDepositTotalPostData>>) => createMutationKey('totalDepositTotalPost', options);

/**
 * Total
 */
export const totalDepositTotalPostMutation = (options?: Partial<Options<TotalDepositTotalPostData>>): UseMutationOptions<TotalDepositTotalPostResponse, TotalDepositTotalPostError, Options<TotalDepositTotalPostData>> => {
    const mutationOptions: UseMutationOptions<TotalDepositTotalPostResponse, TotalDepositTotalPostError, Options<TotalDepositTotalPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await totalDepositTotalPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: totalDepositTotalPostMutationKey(options)
    };
    return mutationOptions;
};
