// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addDepositAddPost, countGoalsCountGet, deleteDepositIdDelete, deleteGoalsIdDelete, getDepositIdGet, getGoalsIdGet, listDepositPost, listGoalsGet, type Options, readRootGet, totalDepositTotalPost, upsertGoalsPost } from '../sdk.gen';
import type { AddDepositAddPostData, AddDepositAddPostError, AddDepositAddPostResponse, CountGoalsCountGetData, CountGoalsCountGetError, CountGoalsCountGetResponse, DeleteDepositIdDeleteData, DeleteDepositIdDeleteError, DeleteDepositIdDeleteResponse, DeleteGoalsIdDeleteData, DeleteGoalsIdDeleteError, DeleteGoalsIdDeleteResponse, GetDepositIdGetData, GetDepositIdGetError, GetDepositIdGetResponse, GetGoalsIdGetData, GetGoalsIdGetError, GetGoalsIdGetResponse, ListDepositPostData, ListDepositPostError, ListDepositPostResponse, ListGoalsGetData, ListGoalsGetError, ListGoalsGetResponse, ReadRootGetData, TotalDepositTotalPostData, TotalDepositTotalPostError, TotalDepositTotalPostResponse, UpsertGoalsPostData, UpsertGoalsPostError, UpsertGoalsPostResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const readRootGetQueryKey = (options?: Options<ReadRootGetData>) => createQueryKey('readRootGet', options);

/**
 * Read Root
 */
export const readRootGetOptions = (options?: Options<ReadRootGetData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof readRootGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRootGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRootGetQueryKey(options)
});

export const countGoalsCountGetQueryKey = (options?: Options<CountGoalsCountGetData>) => createQueryKey('countGoalsCountGet', options);

/**
 * Count
 */
export const countGoalsCountGetOptions = (options?: Options<CountGoalsCountGetData>) => queryOptions<CountGoalsCountGetResponse, CountGoalsCountGetError, CountGoalsCountGetResponse, ReturnType<typeof countGoalsCountGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await countGoalsCountGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: countGoalsCountGetQueryKey(options)
});

export type MutationKey<TOptions extends Partial<Options>> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        tags?: ReadonlyArray<string>;
    }
];

const createMutationKey = <TOptions extends Partial<Options>>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    MutationKey<TOptions>[0]
] => {
    const params: MutationKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl };
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const deleteGoalsIdDeleteMutationKey = (options?: Partial<Options<DeleteGoalsIdDeleteData>>) => createMutationKey('deleteGoalsIdDelete', options);

/**
 * Delete
 */
export const deleteGoalsIdDeleteMutation = (options?: Partial<Options<DeleteGoalsIdDeleteData>>): UseMutationOptions<DeleteGoalsIdDeleteResponse, DeleteGoalsIdDeleteError, Options<DeleteGoalsIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteGoalsIdDeleteResponse, DeleteGoalsIdDeleteError, Options<DeleteGoalsIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteGoalsIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: deleteGoalsIdDeleteMutationKey(options)
    };
    return mutationOptions;
};

export const getGoalsIdGetQueryKey = (options: Options<GetGoalsIdGetData>) => createQueryKey('getGoalsIdGet', options);

/**
 * Get
 */
export const getGoalsIdGetOptions = (options: Options<GetGoalsIdGetData>) => queryOptions<GetGoalsIdGetResponse, GetGoalsIdGetError, GetGoalsIdGetResponse, ReturnType<typeof getGoalsIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGoalsIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGoalsIdGetQueryKey(options)
});

export const listGoalsGetQueryKey = (options?: Options<ListGoalsGetData>) => createQueryKey('listGoalsGet', options);

/**
 * List
 */
export const listGoalsGetOptions = (options?: Options<ListGoalsGetData>) => queryOptions<ListGoalsGetResponse, ListGoalsGetError, ListGoalsGetResponse, ReturnType<typeof listGoalsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listGoalsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listGoalsGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listGoalsGetInfiniteQueryKey = (options?: Options<ListGoalsGetData>): QueryKey<Options<ListGoalsGetData>> => createQueryKey('listGoalsGet', options, true);

/**
 * List
 */
export const listGoalsGetInfiniteOptions = (options?: Options<ListGoalsGetData>) => infiniteQueryOptions<ListGoalsGetResponse, ListGoalsGetError, InfiniteData<ListGoalsGetResponse>, QueryKey<Options<ListGoalsGetData>>, number | Pick<QueryKey<Options<ListGoalsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListGoalsGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listGoalsGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listGoalsGetInfiniteQueryKey(options)
});

export const upsertGoalsPostMutationKey = (options?: Partial<Options<UpsertGoalsPostData>>) => createMutationKey('upsertGoalsPost', options);

/**
 * Upsert
 */
export const upsertGoalsPostMutation = (options?: Partial<Options<UpsertGoalsPostData>>): UseMutationOptions<UpsertGoalsPostResponse, UpsertGoalsPostError, Options<UpsertGoalsPostData>> => {
    const mutationOptions: UseMutationOptions<UpsertGoalsPostResponse, UpsertGoalsPostError, Options<UpsertGoalsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await upsertGoalsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: upsertGoalsPostMutationKey(options)
    };
    return mutationOptions;
};

export const deleteDepositIdDeleteMutationKey = (options?: Partial<Options<DeleteDepositIdDeleteData>>) => createMutationKey('deleteDepositIdDelete', options);

/**
 * Delete
 */
export const deleteDepositIdDeleteMutation = (options?: Partial<Options<DeleteDepositIdDeleteData>>): UseMutationOptions<DeleteDepositIdDeleteResponse, DeleteDepositIdDeleteError, Options<DeleteDepositIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteDepositIdDeleteResponse, DeleteDepositIdDeleteError, Options<DeleteDepositIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteDepositIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: deleteDepositIdDeleteMutationKey(options)
    };
    return mutationOptions;
};

export const getDepositIdGetQueryKey = (options: Options<GetDepositIdGetData>) => createQueryKey('getDepositIdGet', options);

/**
 * Get
 */
export const getDepositIdGetOptions = (options: Options<GetDepositIdGetData>) => queryOptions<GetDepositIdGetResponse, GetDepositIdGetError, GetDepositIdGetResponse, ReturnType<typeof getDepositIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDepositIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDepositIdGetQueryKey(options)
});

export const addDepositAddPostMutationKey = (options?: Partial<Options<AddDepositAddPostData>>) => createMutationKey('addDepositAddPost', options);

/**
 * Add
 */
export const addDepositAddPostMutation = (options?: Partial<Options<AddDepositAddPostData>>): UseMutationOptions<AddDepositAddPostResponse, AddDepositAddPostError, Options<AddDepositAddPostData>> => {
    const mutationOptions: UseMutationOptions<AddDepositAddPostResponse, AddDepositAddPostError, Options<AddDepositAddPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addDepositAddPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: addDepositAddPostMutationKey(options)
    };
    return mutationOptions;
};

export const listDepositPostMutationKey = (options?: Partial<Options<ListDepositPostData>>) => createMutationKey('listDepositPost', options);

/**
 * List
 */
export const listDepositPostMutation = (options?: Partial<Options<ListDepositPostData>>): UseMutationOptions<ListDepositPostResponse, ListDepositPostError, Options<ListDepositPostData>> => {
    const mutationOptions: UseMutationOptions<ListDepositPostResponse, ListDepositPostError, Options<ListDepositPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await listDepositPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: listDepositPostMutationKey(options)
    };
    return mutationOptions;
};

export const totalDepositTotalPostMutationKey = (options?: Partial<Options<TotalDepositTotalPostData>>) => createMutationKey('totalDepositTotalPost', options);

/**
 * Total
 */
export const totalDepositTotalPostMutation = (options?: Partial<Options<TotalDepositTotalPostData>>): UseMutationOptions<TotalDepositTotalPostResponse, TotalDepositTotalPostError, Options<TotalDepositTotalPostData>> => {
    const mutationOptions: UseMutationOptions<TotalDepositTotalPostResponse, TotalDepositTotalPostError, Options<TotalDepositTotalPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await totalDepositTotalPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        },
        mutationKey: totalDepositTotalPostMutationKey(options)
    };
    return mutationOptions;
};
